Clans
discord-userdoccers/discord-userdoccers pull request #224
Opened 2024-05-18 05:57 UTC by Cynosphere

Accuracy is to the best of my ability of looking through client code as I do not currently have access to clans on any guilds.

Verification Form stuff could probably be moved to Membership Screening?

2024-05-18 16:39 UTC, AZthemute commented
I think it would also be worth documenting the new profile setting. I'm not sure if it's possible for me to contribute to your PR without opening a PR on your repo, but either way, here's a couple of API responses:

`PUT /users/@me/clan`
JSON params:
`identity_enabled`: boolean
`identity_guild_id`: ?snowflake

The response is just a partial user object, but for some reason it seems to be from before the user is updated server-side, as enabling my clan returned no clan. Official clients then request your profile for the clan guild anyway, which results in a janky animation when updating your profile lol

`GET /users/@me/join-request-guilds`
Returns an array of partial guilds that you're waiting for a response on.

I also have responses from requesting to join a clan or withdrawing your application, but I'm assuming this builds off of the welcoming screen API anyway, so I won't put it here right now.

Side note but another client I had open now has two blank spaces in the pending applications menu, when only one clan was accepted. Great feature as usual, Discord.

2024-05-19 01:43 UTC, dolfies commented
> The response is just a partial user object, but for some reason it seems to be from before the user is updated server-side, as enabling my clan returned no clan. Official clients then request your profile for the clan guild anyway, which results in a janky animation when updating your profile lol

Yea I noticed this behavior too, kinda funny

> `GET /users/@me/join-request-guilds` Returns an array of partial guilds that you're waiting for a response on
>
> I also have responses from requesting to join a clan or withdrawing your application, but I'm assuming this builds off of the welcoming screen API anyway, so I won't put it here right now.

It's all based on the membership screening/join requests API (which isn't currently documented cuz it was very complex, badly built, and never widely rolled out past the "agree to server rules" thing), but I guess I'll get to it soon

2024-05-19 02:52 UTC, dolfies requested changes

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +| tag                   | string           | The tag of the clan (2-4 letters)                                           |
```suggestion
| tag                   | string           | The tag of the clan (2-4 characters)                                        |
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +| playstyle             | integer          | Number representing a [playstyle](#playstyle)                               |
```suggestion
| playstyle             | integer          | The [playstyle](#playstyle-type) of the clan
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +| description           | string           | Description of the clan, this can be different than the guild's description |
```suggestion
| description           | string           | Description of the clan; this can be different than the guild's description |
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +| game_ids              | array[snowflake] | Array of application IDs                                                    |
```suggestion
| game_ids              | array[snowflake] | The IDs of the applications representing the games the clan plays
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +###### Playstyle
```suggestion
###### Playstyle Type
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +###### Badge Kind
```suggestion
###### Badge Type
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +###### Badge Kind
Wondering if these need descriptions, not sure tho

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +###### Banner Style
Same with these

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +| badge                 | integer          | Number representing a [badge kind](#badge-kind)                             |
```suggestion
| badge                 | integer          | The [badge shown on the clan's tag](#badge-type)                             |
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +| banner                | integer          | Number representing a [banner style](#banner-style)                         |
```suggestion
| banner                | integer          | The [banner representing the clan](#banner-style)                         |
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/discovery.mdx
> +  Guild Clan Discovery Info
```suggestion
  Get Clan
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +  Convert guild to clan
```suggestion
  Create Clan
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +Enables clan features for a guild
```suggestion
Enables clan features for a guild. Returns a 204 empty response on success. Fires a [Guild Update](/topics/gateway-events#guild-update) Gateway event.
```
The response type is a guess based off the fact that the client ignores the response

2024-05-19 02:52 UTC, dolfies commented on pages/resources/clan.mdx
> +Disables a guild's clan features
```suggestion
Disables a guild's clan features. Returns a 204 empty response on success. Fires a [Guild Update](/topics/gateway-events#guild-update) Gateway event.
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/guild.mdx
> +Joins Wumpus Feedback Sqaud through the guild. Requires the `MANAGE_GUILD` permission and the `CLAN` feature. Returns the joined [guild](#guild-object) object on success. Fires a [Guild Create](/topi
```suggestion
Joins Wumpus Feedback Sqaud through the guild. Requires the `MANAGE_GUILD` permission and the [`CLAN` guild feature](#guild-features). Returns the joined [guild](#guild-object) object on success. Fires a [Guild Create](/topics/gateway-events#guild-create) Gateway event.
```

Clan features should be documented too

2024-05-19 02:52 UTC, dolfies commented on pages/resources/user.mdx
> +  Set Clan
```suggestion
  Set Clan Identity
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/user.mdx
> +Sets the current user's clan. Returns a partial [user](#user-object) object of before the update.
```suggestion
Sets the current user's clan. Returns an outdated partial [user](#user-object) object on success.
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/user.mdx
> +| identity_enabled  | boolean    | Whether or not the clan tag is enabled                            |
```suggestion
| identity_enabled  | boolean    | Whether the clan tag is enabled                                  |
```

2024-05-19 02:52 UTC, dolfies commented on pages/resources/user.mdx
> +| identity_guild_id | ?snowflake | The guild ID of the clan to be associated with, or empty to clear |
```suggestion
| identity_guild_id | ?snowflake | The guild ID of the clan to be associated with, if any            |
```

2024-05-24 04:04 UTC, dolfies approved these changes
This is good from me now, ty! Sorry for shoehorning all of join requests in :p

2024-05-26 00:42 UTC, aamiaa approved these changes

2024-05-26 00:44 UTC, aamiaa commented
This is a very well-made pr! Thank you everyone even tho we're literally talking on Discord rn!

2024-05-26 00:46 UTC, Vendicated commented
<a:dolfies:1225091256003203162>

2024-05-26 00:53 UTC, merged