Update create user harvest endpoint
discord-userdoccers/discord-userdoccers pull request #234
Opened 2024-06-16 10:24 UTC by AZthemute

This commit adds the new parameter "backends" to the Create User Harvest endpoint, which allows for selection of specific categories of data to be included in the harvest:
![image](https://github.com/discord-userdoccers/discord-userdoccers/assets/104761702/7dd8d31b-c173-4da3-bae6-6c111a86a3bc)
Currently just a draft PR because I need to test the note more, which involves waiting for discord to actually send the data. There's surprisingly a lot of random discrepancies that I feel like shouldn't be a thing, but I've tried to test as many as possible. I will need to wait for the data first in order to verify though.

2024-06-16 15:21 UTC, dolfies requested changes

2024-06-16 15:21 UTC, dolfies commented on pages/resources/user.mdx
> +| Servers        | All servers the user is currently a member of |
```suggestion
| Servers        | All guilds the user is currently a member of |
```

2024-06-16 15:21 UTC, dolfies commented on pages/resources/user.mdx
> +| Activities     | Activity information                          |
```suggestion
| Activities     | First-party embedded activity information                          |
```

2024-06-22 11:11 UTC, AZthemute commented
> Currently just a draft PR because I need to test the note more, which involves waiting for discord to actually send the data. There's surprisingly a lot of random discrepancies that I feel like shouldn't be a thing, but I've tried to test as many as possible. I will need to wait for the data first in order to verify though.

Nearly a week later and I've received nothing from Discord, which is just telling me that they will never send the data. I'll unmark this as a draft since I'd rather get the information out earlier. But feel free to test what certain values (e.g. no body, empty backends, null for backends, invalid backends) do since my assumption may be wrong.

2024-06-22 15:40 UTC, dolfies approved these changes
tysm! maybe eventually we can have a separate page with an overview of data pkg contents

2024-06-22 15:40 UTC, merged