Document system welcome messages for CLAN servers
discord-userdoccers/discord-userdoccers pull request #273
Opened 2024-09-01 17:48 UTC by owocado

2024-09-01 18:06 UTC, owocado commented on pages/resources/message.mdx
what should the new heading be called

2024-09-01 18:08 UTC, owocado commented on pages/resources/message.mdx
if we add new heading, this section in https://docs.discord.sex/resources/message#message-type will also require new jump link for clarification
![image](https://github.com/user-attachments/assets/ff008e39-f904-49d8-bf1a-c905edea81ac)

2024-09-04 15:57 UTC, dolfies requested changes

2024-09-04 15:57 UTC, dolfies commented on pages/resources/message.mdx
> +See the 2nd table below for system welcome messages that shows up in CLAN servers.
```suggestion
However, if the guild has the [`CLAN` feature](/resources/guild#guild-features), the same is determined via dividing the message's `timestamp` with millisecond precision by modulo 10.

See the 2nd table below for the system welcome messages specific to clans.
```

2024-09-04 15:57 UTC, dolfies commented on pages/resources/message.mdx
>  The type of rendered message is determined via converting the message's `timestamp` to a unix timestamp with millisecond precision, modulo 13.
```suggestion
 Usually, the type of rendered message is determined via converting the message's `timestamp` to a unix timestamp with millisecond precision, modulo 13.
```

2024-09-04 15:58 UTC, dolfies commented on pages/resources/message.mdx
Yup, moving the new clan welcome message description in between the tables would be perfect

2024-09-04 16:07 UTC, owocado commented on pages/resources/message.mdx
ok done, how does it look now :3

2024-09-05 02:03 UTC, dolfies approved these changes

2024-09-05 02:03 UTC, merged

2024-09-05 02:03 UTC, dolfies commented
ty!