experiments.mdx: added ?platform for /experiments query
discord-userdoccers/discord-userdoccers pull request #283
Opened 2024-10-02 19:27 UTC by DzikStar

2024-10-02 19:55 UTC, splatterxl commented
Can you add an enum for this

2024-10-02 19:56 UTC, splatterxl commented on pages/topics/experiments.mdx
> +| platform?               | string  | Includes experiments from provided platform enum in the returned data |
```suggestion
| platform?               | string  | Limits the response to experiments targeting the selected platform |
```

2024-10-02 22:00 UTC, splatterxl commented
> Also. Coming back to the comment where you corrected the line - I wanted to point out that after adding `?platform=DEVELOPER_PORTAL` it combines default response with platform response. 
Oh, didn't know that -- does it add an extra field or just inserts into the array?

> Another thing, maybe I'll add tomorrow. Using `platform` seems to require authorization to get request response.
Does this also accept a fingerprint header?

2024-10-07 01:52 UTC, dolfies commented on pages/topics/experiments.mdx
> +| platform?               | string  | Includes experiments from provided platform enum in the returned data |
```suggestion
| platform?               | string  | Supplements the response with experiments from the given [platform](#experiment-platform) |

###### Experiment Platform

| Value | Description |
| ------ | ------------ |
| DEVELOPER_PORTAL | The developer portal |
```

2024-10-12 18:29 UTC, splatterxl requested changes

2024-10-12 18:29 UTC, splatterxl commented on pages/topics/experiments.mdx
> +| platform?               | string  | Supplements the response with experiments from the given [platform](#experiment-platform) |
```suggestion
| platform?               | string  | Whether to also include experiments for the given [platform](#experiment-platform) |
```

It's still unclear to me what the param actually does... 

Maybe worth it to add a sentence outside the table to clarify in what situation it's sent and why the data isn't included by default?

2024-12-11 04:36 UTC, merged