Add new channel flag (OBFUSCATED)
discord-userdoccers/discord-userdoccers pull request #287
Opened 2024-10-15 19:05 UTC by BoryaGames

Discord has added a new channel flag in [this commit](https://github.com/Discord-Datamining/Discord-Datamining/commit/4338e84cf234c6d4ad008bbe1ef7dc2dec877d48#commitcomment-147964318).
![image](https://github.com/user-attachments/assets/cabc4ea1-ada0-4497-9dca-b83d766e8617)

2024-10-15 19:12 UTC, splatterxl requested changes

2024-10-15 19:12 UTC, splatterxl commented on pages/resources/channel.mdx
> +| 1 << 17     | OBFUSCATED                                 | This channel's name is obfuscated because user doesn't have access to it
```suggestion
| 1 << 17     | OBFUSCATED                                 | This channel is unavailable for the current user                                                                                        |
```

Can you add a footnote saying something like ``The channel's name is always returned as `___hidden___`.``

2024-12-13 23:24 UTC, splatterxl requested changes

2024-12-13 23:24 UTC, splatterxl commented on pages/resources/channel.mdx
> +| 1 << 17     | OBFUSCATED ^2^                             | This channel is unavailable for the current user
```suggestion
| 1 << 17     | OBFUSCATED ^2^                             | This channel is unavailable for the current user, and has its details obfuscated                                                                                                                |
```

2024-12-13 23:24 UTC, splatterxl commented on pages/resources/channel.mdx
> +^2^ The channel's name is always returned as `___hidden___`.
```suggestion
^2^ The channel's name and topic are always returned as `___hidden___`.
```

2024-12-14 13:45 UTC, splatterxl approved these changes

2024-12-14 14:26 UTC, BoryaGames commented
Resolved merge conflict

2024-12-14 18:30 UTC, Dziurwa14 approved these changes

2024-12-14 18:32 UTC, mantikafasi approved these changes

2024-12-14 18:39 UTC, voidfill commented
LGTM

2024-12-14 22:40 UTC, splatterxl approved these changes

2024-12-14 22:40 UTC, merged

2024-12-14 22:41 UTC, splatterxl commented
Thank you!