Custom logo
discord-userdoccers/discord-userdoccers pull request #43
Opened 2023-02-28 22:23 UTC by wingio

![Userdoccers Logo](https://user-images.githubusercontent.com/44992537/221995150-555e94b8-3ca1-4749-8320-99ccebe8831c.png)

:trollface:

2023-02-28 22:24 UTC, Dziurwa14 commented
🧌

2023-02-28 23:50 UTC, dolfies requested changes
Looks good! CI isn't too happy though; once that passes I can merge.

2023-02-28 23:54 UTC, wingio commented
i can't see why it failed, so i can't debug

2023-03-01 00:07 UTC, dolfies approved these changes
wingwong 🥰

2023-03-01 00:07 UTC, merged