document message type 35 (nitro referrals)
discord-userdoccers/discord-userdoccers pull request #93
Opened 2023-05-17 01:47 UTC by hackermondev

2023-05-17 01:54 UTC, dolfies requested changes

2023-05-17 01:54 UTC, dolfies commented on pages/resources/message.mdx
> +| 35     | PREMIUM_REFERRAL                             | A message sent when a user gifts a nitro referral                         | "{content}"
```suggestion
| 35     | PREMIUM_REFERRAL                             | A message sent when a user gifts a premium (Nitro) referral              | "{content}"                                                                                                                                                                      | true      |
```

2023-05-17 02:31 UTC, hackermondev commented
@dolfies recheck new changes 🙏

2023-05-17 02:49 UTC, dolfies requested changes
Thanks for the PR! Just a few nitpicks. This new resource also needs to be added to the route header, but I can do that myself.

2023-05-17 02:49 UTC, dolfies commented on pages/resources/premium-referral.mdx
> +| referrals_remaining   | number                                                      | Amount of referrals you have remaining                                                                   |
```suggestion
| referrals_remaining   | number                                                      | The amount of referrals remaining                                                                |
```

2023-05-17 02:49 UTC, dolfies commented on pages/resources/premium-referral.mdx
> +
Unnecessary
```suggestion
```

2023-05-17 02:49 UTC, dolfies commented on pages/resources/premium-referral.mdx
> +| trial_id              | snowflake                                                   | The billing trial id                                                                                     |
```suggestion
| trial_id              | snowflake                                                   | The trial ID associated with the referral                                                                 |
```

2023-05-17 02:49 UTC, dolfies commented on pages/resources/premium-referral.mdx
> +| subscription_trial    | billing subscription trial (todo)                           | The billing subscription for the the referral                                                            |
```suggestion
| subscription_trial    | subscription trial object (todo)                            | The subscription trial associated with the referral                                              |
```

2023-05-17 02:49 UTC, dolfies commented on pages/resources/premium-referral.mdx
> +| referrer_id           | snowflake                                                   | The user who created the referral                                                                        |
```suggestion
| referrer_id           | snowflake                                                   | The ID of the user who created the referral                                                           |
```

2023-05-17 02:49 UTC, dolfies commented on pages/resources/premium-referral.mdx
> +
Unnecessary
```suggestion
```

2023-05-17 02:49 UTC, dolfies commented on pages/resources/premium-referral.mdx
> +| sent_user_ids         | array of user ids                                           | Users you have sent a referral to                                                                        |
```suggestion
| sent_user_ids         | array of user ids                                           | The users that have been referred                                                                        |
```

2023-05-17 02:49 UTC, dolfies commented on pages/resources/premium-referral.mdx
> +###### Example Premium Referral
Please move this to be under the relevant structure

2023-05-17 02:49 UTC, dolfies commented on pages/resources/premium-referral.mdx
> +<RouteHeader method="GET" url="/users/@me/referrals/eligibility">
Please move this to the top of the endpoint list

2023-05-18 03:14 UTC, dolfies approved these changes
ty!!

2023-05-18 03:14 UTC, merged